### ISSUE TITLE
Russian locales

### ISSUE THREAD

**Issue by pr0l** [rgtk/redmine_impersonate#9]
Hello, I would like to thank you for your plugin. Below is the Russian translation for the plugin. I would like to ask you to add an icon before the button to more closely match the style of the Redmain. Thank you.
```
cat ./ru.yml 
ru:
  notice_impersonating_user: "Представляемся как %{user}"
  button_impersonate: "Представиться"

```
